// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApJjszcONkSP5rrBsNrTyIu0gydIlA6tw',
    appId: '1:194566883429:web:4c79393231aa5784d71e8c',
    messagingSenderId: '194566883429',
    projectId: 'bit-weather',
    authDomain: 'bit-weather.firebaseapp.com',
    storageBucket: 'bit-weather.appspot.com',
    measurementId: 'G-C2HJQRLYQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChN7i7Ui3Kjwp4nM85TknoMKzvrHUULsM',
    appId: '1:194566883429:android:22ad199dac7c2409d71e8c',
    messagingSenderId: '194566883429',
    projectId: 'bit-weather',
    storageBucket: 'bit-weather.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJZ5Wh9jqD9nuG2tcobCw3AhZIdt33waM',
    appId: '1:194566883429:ios:81b5e98ea4a26070d71e8c',
    messagingSenderId: '194566883429',
    projectId: 'bit-weather',
    storageBucket: 'bit-weather.appspot.com',
    iosBundleId: 'com.example.bitweather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJZ5Wh9jqD9nuG2tcobCw3AhZIdt33waM',
    appId: '1:194566883429:ios:c12954cf456f9bfbd71e8c',
    messagingSenderId: '194566883429',
    projectId: 'bit-weather',
    storageBucket: 'bit-weather.appspot.com',
    iosBundleId: 'com.example.bitweather.RunnerTests',
  );
}
